services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  nocturne-postgres-server:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "nocturne-postgres-data"
        read_only: false
    networks:
      - "aspire"
  nocturne-api:
    image: "${NOCTURNE_API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTPS_PORTS: "${NOCTURNE_API_PORT}"
      ConnectionStrings__nocturne-postgres: "Host=nocturne-postgres-server;Port=5432;Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD};Database=nocturne-rhys"
      NOCTURNE_POSTGRES_HOST: "nocturne-postgres-server"
      NOCTURNE_POSTGRES_PORT: "5432"
      NOCTURNE_POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
      NOCTURNE_POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      NOCTURNE_POSTGRES_URI: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@nocturne-postgres-server:5432/nocturne-rhys"
      NOCTURNE_POSTGRES_JDBCCONNECTIONSTRING: "jdbc:postgresql://nocturne-postgres-server:5432/nocturne-rhys"
      NOCTURNE_POSTGRES_DATABASENAME: "nocturne-rhys"
      DemoService__Enabled: "false"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "nocturne-api"
    expose:
      - "${NOCTURNE_API_PORT}"
    depends_on:
      nocturne-postgres-server:
        condition: "service_started"
    networks:
      - "aspire"
  watchtower:
    image: "ghcr.io/nicholas-fedor/watchtower:latest"
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "86400"
      WATCHTOWER_INCLUDE_STOPPED: "false"
      WATCHTOWER_REVIVE_STOPPED: "false"
    volumes:
      - type: "bind"
        target: "/var/run/docker.sock"
        source: "/var/run/docker.sock"
        read_only: false
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  nocturne-postgres-data:
    driver: "local"
